on:
  pull_request:
    types: [opened, edited, reopened]
    branches: 'main'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./.github/workflows
    steps:
      - uses: actions/checkout@v4
      - run: |
          ruby pre-push